### ISSUE TITLE
Less verbosity on the logs

### ISSUE THREAD

**Issue by nikolaigauss** [awslabs/aws-service-catalog-puppet#269]
Please include a link to your expanded manifest, the full contents of your AWS CodeBuild output N/A

Please ensure you are using the latest version and have run a validate command on your manifest file
N/A

# Steps to reproduce
1. Run puppet.
2. Try to find a traceback should an error happen

# Expected results
1. Finding the stacktrace and troubleshoot.

# Actual results
1. Impossible to go through the amount of logs, our manifest has 20 launches only and it writes over 10000 lines.

One of the main problems is that the manifest is being written in the output every time, that's redundant and it makes the log much hard to read.

**Comment by eamonnfaherty** [comment]
Thanks for reporting an issue.

Have you subscribed to the sns topic for stack updates? https://aws-service-catalog-puppet.readthedocs.io/en/latest/puppet/notifications.html  This will give you all stack updates from all provisioning.  You can add filters yourself to only listen to errors.

You can also enable AWS OpsCenter: https://aws-service-catalog-puppet.readthedocs.io/en/latest/puppet/faq.html#how-do-i-enable-opscenter-support. This will report all errors to OpsCenter as an OpsItem with the stack trace to help debug what has gone wrong.

The logs are verbose by design to help resolve issues quickly.  You can export the logs and search through them using the command: https://aws-service-catalog-puppet.readthedocs.io/en/latest/puppet/using_the_cli.html#export-puppet-pipeline-logs. The export also includes timestamps to help diagnose timing issues.

I will reduce the frequency of printing of the manifest in the next release.  If you see any other changes like that please let me know.

**Comment by nikolaigauss** [comment]
Hey, I believe this will be good enough, I'll try those solutions you mentioned and will raise another issue if I'm still struggling to find debug information, anyway printing the manifest less frequently will deffo help :).
