### ISSUE TITLE
can't deploy stack

### ISSUE THREAD

**Issue by SergiyShevchenk** [awslabs/aws-service-catalog-puppet#465]
I have catalog factory and puppet deployed in account YYYYYYYYYY, where all pipeline are happy except puppet one.
Tyring to provision stack however getting this error. Not sure what role should i create on the XXXXXXX account which is master account where i don't actually want my stack to be provisioned on but only on to account AAAAAAAAA. here is my code of  servicecatalogpuppet/manifest.yaml

`

accounts:
--
2 | - account_id: &AAAAAAAA_accoubt_id 'AAAAAAAAA'
3 | name: "AAAAAAAAA-account"
4 | default_region: "us-east-2"
5 | regions_enabled:
6 | - "us-east-2"
7 | tags:
8 | - "type:prod"
9 |  
10 | stacks:
11 | delete-default-vpc:
12 | name: "vpc"
13 | version: "v1"
14 | capabilities:
15 | - CAPABILITY_NAMED_IAM
16 | deploy_to:
17 | tags:
18 | - tag: "type:prod"
19 | regions: "default_region"

`
not even sure why is the master account XXXXXXXXX even mentioned ;-(

botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the AssumeRole operation: User: arn:***:sts::YYYYYYYYYY:assumed-role/PuppetDeployRole/AWSCodeBuild-15b8bc23-8a08-4fbe-bdda-bffbf8bdc671 is not authorized to perform: sts:AssumeRole on resource: arn:***:iam::XXXXXXXXX:role***PuppetOrgRoleForExpandsXXXXXXXXX
--
216 |  
217 | [Container] 2022/01/28 19:56:44 Command did not exit successfully servicecatalog-puppet --info expand --parameter-override-file $CODEBUILD_SRC_DIR_ParameterisedSource/parameters.yaml manifest.yaml exit status 1
218 | [Container] 2022/01/28 19:56:44 Phase complete: PRE_BUILD State: FAILED
219 | [Container] 2022/01/28 19:56:44 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: servicecatalog-puppet --info expand --parameter-override-file $CODEBUILD_SRC_DIR_ParameterisedSource/parameters.yaml manifest.yaml. Reason: exit status 1

**Comment by ssheff** [comment]
hi there again. please assist/advice

**Comment by eamonnfaherty** [comment]
Hi @SergiyShevchenk thanks for reaching out and sorry for the delay getting back to you.  

In order to help you it would be great to get the following questions answered:

1. Is this a fresh install or have you made a change that meant the puppet pipeline went from succeeding to failing?
2. Did you want to use AWS Organizations support?  It is useful if you want to use OUs in your manfiest file otherwise it may be simpler to not use it.
3. If you want to use it, have you prepared your AWS Organizations management account - the instructions are here: https://service-catalog-tools-workshop.com/installation/30-service-catalog-puppet/10-using-aws-organizations.html 
4. Can you confirm that is your entire manifest file

**Comment by ssheff** [comment]
Hi @eamonnfaherty and thanks for the reply.
1. brand new install
2. nope no org support
3. yes, t is prepared and service catalog deployed successfully as well as associated pipelines ran with no errors
4. yes and no. i do have the manifest file. But there is a repo structure with a few repos one for puppet one for the factory. which one are we talking about?

**Comment by eamonnfaherty** [comment]
please confirm the trust policy on your role arn::iam::XXXXXXXXX:role***PuppetOrgRoleForExpandsXXXXXXXXX has the correct account listed.  It should be the account where you have installed puppet.

if this is the correct id then reopen this.
